name: ass_pm
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  curved_navigation_bar: ^1.0.0
  flutter_native_splash: ^2.3.7
  like_button: ^2.0.5
  clippy_flutter: ^2.0.0-nullsafety.1
  flutter_rating_bar: ^4.0.1
  flutter:
    sdk: flutter
  icon_forest: ^1.1.8
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/BBQbacon hotdogs.jpg
    - images/burger.jpg
    - images/burgerr.jpg
    - images/doblebeff.jpg
    - images/hotdogs.jpg
    - images/minuman.jpg
    - images/logo.jpg
    - images/allmenu.jpg


